### ISSUE TITLE
pypi source package is missing 'pyann/annlib/annlib.pyx'

### ISSUE THREAD

**Issue by xfoxfu** [annacnev/pyann#4]
```
$ pip install pyann
Collecting pyann
  Using cached pyann-0.0.1.tar.gz (58 kB)
    ERROR: Command errored out with exit status 1:
     command: /usr/bin/python3 -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-r_18n13x/pyann/setup.py'"'"'; __file__='"'"'/tmp/pip-install-r_18n13x/pyann/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-install-r_18n13x/pyann/pip-egg-info
         cwd: /tmp/pip-install-r_18n13x/pyann/
    Complete output (11 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-r_18n13x/pyann/setup.py", line 40, in <module>
        ext_modules=cythonize([annlib_extension]),
      File "/home/v-yuzefu/.local/lib/python3.8/site-packages/Cython/Build/Dependencies.py", line 965, in cythonize
        module_list, module_metadata = create_extension_list(
      File "/home/v-yuzefu/.local/lib/python3.8/site-packages/Cython/Build/Dependencies.py", line 815, in create_extension_list
        for file in nonempty(sorted(extended_iglob(filepattern)), "'%s' doesn't match any files" % filepattern):
      File "/home/v-yuzefu/.local/lib/python3.8/site-packages/Cython/Build/Dependencies.py", line 114, in nonempty
        raise ValueError(error_msg)
    ValueError: 'pyann/annlib/annlib.pyx' doesn't match any files
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
```

The package on pypi lists as

```
pyann-0.0.1
├── PKG-INFO
├── README.md
├── pyann
│   ├── __about__.py
│   ├── __init__.py
│   ├── annlib
│   │   ├── __init__.py
│   │   ├── annlib.cpp
│   │   └── lib
│   │       └── ann2.cpp
│   ├── nn2.py
│   └── tests
│       ├── __init__.py
│       └── test_nn2.py
├── pyann.egg-info
│   ├── PKG-INFO
│   ├── SOURCES.txt
│   ├── dependency_links.txt
│   ├── requires.txt
│   └── top_level.txt
├── setup.cfg
└── setup.py
```

**Comment by annacnev** [comment]
@xfoxfu ah, good catch! The source tarball on the pypi page does not include `pyann/annlib/annlib.pyx` and I am really not sure why that is missing. I will update the tarball there. In the meantime, you should be able to clone this repo and build from source the same way because this repo does have the .pyx file in it. If you have any issues with doing that, feel free to open another issue! Thanks for bringing this to my attention- appreciate the feedback so much!
